version: '2'

services:
  lapiwe.onderhoudservice.facade:
    image: lapiwe/lapiwe.onderhoudservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6050:80
    links:
      - onderhoud-db:db
    networks:
      - eventbus-network

  onderhoud-db:
    image: "mysql:latest"
    container_name: "lapiwe_onderhoudservice_mysql"
    volumes: 
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: onderhoud
      MYSQL_ROOT_PASSWORD: 12344321
    ports:
      - 6052:3306
    networks:
      - eventbus-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "lapiwe_onderhoudservice_phpmyadmin"
    links:
      - onderhoud-db:db
    ports:
      - 6051:80
    networks: 
      - eventbus-network

networks:
  eventbus-network:
    external:
      name: eventbus-network
