version: '2'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5673:5672
            - 12345:15672
            - 8080:8080
        networks: 
            - eventbus-network

networks:
  eventbus-network:
    external:
      name: eventbus-network