version: '2'

services:
  lapiwe.klantbeheerservice.facade:
    image: lapiwe/lapiwe.klantbeheerservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6020:80
    links:
      - klantbeheer-db:db
    networks:
      - eventbus-network

  klantbeheer-db:
    image: "mysql:latest"
    container_name: "lapiwe_klantbeheerservice_mysql"
    volumes: 
      - "./.data/db:/var/lib/mysql"
    environment:
      'ConnectionStrings:DataAccessMySqlProvider': server=db;userid=admin;password=1234;database=onderhoud;
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: klantbeheer
      MYSQL_ROOT_PASSWORD: 12344321
    ports:
      - 6022:3306
    networks:
      - eventbus-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "lapiwe_klantbeheerservice_phpmyadmin"
    links:
      - klantbeheer-db:db
    ports:
      - 6021:80
    networks: 
      - eventbus-network

networks:
  eventbus-network:
    external:
      name: eventbus-network
