version: '2'

services:
  lapiwe.klantbeheerservice.facade:
    image: user/lapiwe.klantbeheerservice.facade${TAG}
    build:
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql
    container_name: klantbeheerservice-mysql
    environment:
      MYSQL_PASSWORD: klantbeheer
      MYSQL_DATABASE: klantbeheer
      MYSQL_USER: klantbeheer
      MYSQL_ROOT_PASSWORD: klantbeheer
    ports:
      - 6022:3306
    networks: 
      - eventbus-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: klantbeheerservice-phpmyadmin
    links:
     - mysql:db
    ports:
     - 6021:80
    networks: 
      - eventbus-network

networks:
  eventbus-network:
    external:
      name: eventbus-network
